applications:
  ceph-csi:
    charm: ceph-csi
    channel: stable

relations:
  - [ '__K8S_CONTROLLER_CHARM__:ceph-k8s-info', 'ceph-csi:kubernetes-info' ]
  - [ 'ceph-csi:ceph-client', 'ceph-mon:client']

